### PR TITLE
xml

### PR DESCRIPTION
**Pull request by cwulfman**
An xml version of the jetsons EDF

### CODE REVIEW

**Review by ion-oset — CHANGES_REQUESTED** [review]
Can you change the base branch of the PR to be `jetsons` instead of `main`?

See: [Changing the base branch of a pull request
](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

**Comment by ion-oset** [comment]
XML ports of the Jetsons JSON CVR and EDF.

Note: The tooling used to validate the XML (Oxygen XML) validates more in-depth than the Python `jsonschema` module.

**Comment by cwulfman** [comment]
I believe Oxygen uses Saxon HE <https://www.saxonica.com/html/documentation10/about/whatis.html> by default.

On Jun 9, 2021, at 12:56 PM, ion-oset ***@***.******@***.***>> wrote:

Note: The tooling used to validate the XML (Oxygen XML) validates more in-depth than the Python jsonschemamodule.

**Comment by trustthevote** [comment]
Cliff,
    
    Here is the San Mateo form to give you an idea of type of eye candy
    to use at top and bottom, to show that we can have a state-specific
    template that incorporates typical eye candy and also has all the
    data required. In the case of the SM form, the military/overeseas
    address is not relevant to our case; and while name address and
    signature are required, other fields are required in our case. 
    
    So let's see if we can come up with a Gadget County statement, while
    recognizing that each state's template is going to have their own
    wording.
    
    "Oath of Voter
    
    I _____ _____ do swear and affirm that: I am a registered voter of
    Gadget County; I am qualified to vote in this election; I have not
    applied, and do not intend to apply for an absentee ballot in any
    other jurisdiction in this election; I have truthfully provided my
    name, signature and other personal information to be used to
    determine my voter qualification and the eligibility of my absentee
    ballot to be counted. I understand that such name, signature, and
    personal information will be separated from my voted ballot to
    maintain its anonymity at the onset of the ballot tabulation process
    and thereafter. My last known Gadget County address is: "
    
    With that, the two blanks are first name and last name (no need for
    prompts under the line). Then after the above text, underline fields
    for:
    
    Street Address (half page width), Apt/Unit (maybe 8 chars), City
    (the rest of the line width except for 5 chars), ZIP (5 chars)
    
    After that, we need an about 20 char field for "Driver's License or
    State ID Card Number" and a 10 char field for "Social Security
    Number"
    
    Below that line, we need a line with 2 checkboxes. First checkbox "I
    do not have a Driver's License or State ID Card Number" and second
    is "I do not have a Social Security Number" but the checkboxes need
    to be aligned with the text on the previous line.
    
    Then we need some horizontal space in which you can insert a photo
    of a front/back of a driver's license -- you can use images from
    dps.mn.gov found by search "sample minnesota driver's license back
    side" placed beside one another. Then some more boilerplate:
    
    "I declare under penalty of perjury under the laws of the State of
    Thefuture that the foregoing declarations are, to the best of my
    knowledge and belief, true and correct."
    
    Then a line with a half-line-width field for "Signature of Voter"
    and half line for date.
    Then a line with a half-line-width field for "Signature of Witness"
    and half line for "Name of Witness"
    Any kind of scrawlish image will do for the signatures.
    
    Then after that any vertical space remaining, and finally a footer
    with address phone fax email web similar to San Mateo.
    
    Have fun making up Jetsonsish names for people and things!
    
    EJS

**Comment by ion-oset** [comment]
@cwulfman I've turned the above text into issue #9 and assigned it to you.

**Pull request merged**
